---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "samtools_consensus"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::samtools=1.20"
