---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::ipykernel=6.0.3
  - conda-forge::jupytext=1.11.4
  - conda-forge::matplotlib=3.4.2
  - conda-forge::nbconvert=6.1.0
  - conda-forge::papermill=2.3.3
