---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::gubbins=3.3.5
  - conda-forge::python=3.9.19
  - conda-forge::setuptools=69.2.0
