---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconda::jvarkit=2024.08.25
