---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12.2
  - bioconda::gmm-demux=0.2.2.3
  - numpy=1.26.4
  - pandas=2.2.1
  - scipy=1.12.0
  - scikit-learn=1.4.1
