---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "gmmdemux"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::gmm-demux=0.2.2.3"
