---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::gmm-demux=0.2.2.3
  - conda-forge::numpy=1.26.4
  - conda-forge::pandas=2.2.1
  - conda-forge::python=3.12.2
  - conda-forge::scikit-learn=1.4.1
  - conda-forge::scipy=1.12.0
