---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::fast2q=2.7.2
  - conda-forge::setuptools=75.8.0
  - conda-forge::python=3.12.8
