---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bowtie2=2.5.4
  - bioconda::bowtie=1.3.1
  - bioconda::bwa=0.7.19
  - bioconda::fastq-screen=0.16.0
  - bioconda::minimap2=2.30
