---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.3.2
  - bioconda::bioconductor-genomicfeatures=1.54.1
  - bioconda::ribowaltz=2.0
  - r-dplyr=1.1.4
