name: proteus_readproteingroups
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.2.1
  - bioconda::r-proteus-bartongroup=0.2.16
  - conda-forge::r-plotly=4.10.2
  - bioconda::bioconductor-limma=3.54.0
