---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::anndata=0.10.9
  - conda-forge::jaxlib=0.4.31
  - conda-forge::python=3.12.7
  - conda-forge::scvi-tools=1.2.0
