---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::artic=1.6.2
  - bioconda::htslib=1.17 # can't be updated due to dependency issues
