---
# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/master/modules/environment-schema.json
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconda::hifi_trimmer=2.1.0
  - bioconda::htslib=1.23
  - bioconda::samtools=1.23
