---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::hmmer=3.4
  - bioconda::prodigal=2.6.3
  - conda-forge::pandas=1.3.5
  - conda-forge::parallel=20251122
  - conda-forge::pip=24.3.1
  - pip:
      - traitar3==0.1.1
