---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::ismapper=2.0.2
  - conda-forge::python=3.9.6
  - conda-forge::setuptools=49.6.0
