---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "fastqscreen_fastqscreen"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::fastq-screen=0.15.3"
  - bioconda::perl-gdgraph=1.54
