---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "seurat_multiseq"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::r-seurat=3.0.2"
