---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::ribotricer=1.3.3
  - conda-forge::python=3.10
  - conda-forge::scipy=1.10.0
