---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - bwa-mem2=2.2.1
  - htslib=1.19.1
  - samtools=1.19.2

# pipelines:
#  - sarek
