---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "custom_catadditionalfasta"
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.9.5
