---
name: lsa_cosine
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.5.2
  - conda-forge::r-lsa=0.73.4
  - conda-forge::r-pheatmap=1.0.13
  - conda-forge::r-optparse=1.7.5
  - conda-forge::r-readr=2.1.6
