---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::diamond=2.1.9
  - bioconda::orthofinder=2.5.5
  - conda-forge::python=3.10.* # orthofinder 2.5.5 supported only up to python 3.10
