---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12.9
  - bioconda::checkm2=1.1.0
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.15.2
  - scikit-learn=1.6.1
  - tensorflow=2.17.0
  - keras=3.9.0
