---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::checkm2=1.1.0
  - conda-forge::keras=3.9.0
  - conda-forge::numpy=1.26.4
  - conda-forge::pandas=2.2.3
  - conda-forge::python=3.12.9
  - conda-forge::scikit-learn=1.6.1
  - conda-forge::scipy=1.15.2
  - conda-forge::tensorflow=2.17.0
