---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "tsebra"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::tsebra=1.1.2.4"
