channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::r-cnaqc=1.1.3
  - bioconda::r-mobster=0.1.1
  - conda-forge::r-cli=3.6.5
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-ggplot2=3.5.2
