---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - bioconda
  - conda-forge
  - milaboratories
dependencies:
  - milaboratories::mixcr=4.7.0