---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "foldmason_easymsa"
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::foldmason=1.763a428
  - conda-forge::pigz=2.8
