---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "poolsnp"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::poolsnp=1.0.1"
