---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::optitype=1.3.5
  - conda-forge::coincbc=2.10.10
  # Pin pytables<3.10 to avoid Python 3.13 compatibility issues with OptiType's HDF5 files
  - conda-forge::pytables=3.9.2
