---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "ale"
channels:
  - conda-forge
  - bioconda
  - tanghaibao
dependencies:
  - "bioconda::ale=20180904"
