---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::bzip2=1.0.8
  - conda-forge::gzip=1.13
  - conda-forge::lzip=1.21
  - conda-forge::lzop=1.04
  - conda-forge::tar=1.34
  - conda-forge::xz=5.2.6
  - conda-forge::zstd=1.5.6
