channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconda::r-cnaqc=1.1.3
  - bioconda::r-viber=1.0.0
  - conda-forge::r-cli=3.6.5
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-ggplot2=3.5.2
  - conda-forge::r-ggpubr=0.6.1
  - conda-forge::r-tidyr=1.3.1
