---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::htslib=1.23
  - bioconda::pretextmap=0.2.2
  - bioconda::samtools=1.23
