---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "trycycler_cluster"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::trycycler=0.5.3"
