---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - bioconda
  - conda-forge

dependencies:
  - bioconda::alevin-fry=0.11.2
  - bioconda::piscem=0.12.2
  - bioconda::salmon=1.10.3
  - bioconda::simpleaf=0.19.4
