channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-dnacopy=1.80.0
  - bioconda::bioconductor-org.hs.eg.db=3.20.0
  - bioconda::bioconductor-purecn=2.12.0
  - bioconda::bioconductor-txdb.hsapiens.ucsc.hg19.knowngene=3.2.2
  - bioconda::bioconductor-txdb.hsapiens.ucsc.hg38.knowngene=3.20.0
  - bioconda::gatk4=4.6.2.0
  - bioconda::r-pscbs=0.68.0
  - conda-forge::procps-ng=4.0.4
  - conda-forge::r-futile.logger=1.4.3
  - conda-forge::r-mass=7.3_65
  - conda-forge::r-optparse=1.7.5
