---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::cyvcf2=0.31.4
  - conda-forge::asyncpg=0.29.0
  - conda-forge::jq=1.7
  - conda-forge::pydantic=2.6.0
  - conda-forge::rich=13.7.0
  - conda-forge::typer=0.12.0
  - pip:
      - vcf-pg-loader==0.5.3
