---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::vcf-pg-loader=0.5.3=pyhdfd78af_0
  - conda-forge::jq=1.7
