---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - numpy=1.26
  - pip=25.2
  - python=3.9
  - pip:
      - checkqc==4.0.3
      - interop==1.3.2
