channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::sample-sheet=0.13.0
  - conda-forge::numpy=2.2.4
  - conda-forge::pandas=2.2.2
  - conda-forge::pip=25.2
  - conda-forge::python=3.10.19
  - conda-forge::tornado=6.3.2
  - conda-forge::xmltodict=0.13.0
  - pip:
      - checkQC==4.1.0
      - interop==1.4.0
      - jsonschema==4.26.0
      - samshee==0.2.12
