channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::fusion-inspector=2.10.0
  - bioconda::igv-reports=1.14.1
  - bioconda::perl-json-xs=4.03
  - bioconda::pysam=0.22.1
  - conda-forge::perl-carp-assert=0.21
  - conda-forge::pip==24.3.1
  - pip:
      - intervaltree==3.1.0
