---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-fs=1.6.4
  - conda-forge::r-ggplot2=3.4.4
  - conda-forge::r-nacho=2.0.6
  - conda-forge::r-optparse=1.7.5
  - conda-forge::r-readr=2.1.5
  - conda-forge::r-tidyr=1.3.0
