name: homer_maketagdirectory
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::homer=4.11
  - bioconda::samtools=1.11
  - conda-forge::r-base=4.0.2
  - bioconda::bioconductor-deseq2=1.30.0
  - bioconda::bioconductor-edger=3.32.0
  - anaconda::perl=5.26.2
