---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "last_mafconvert"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::last=1571"
