---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconda::last=1608
  - bioconda::samtools=1.21
