channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::r-base=4.2.3
  - conda-forge::r-data.table=1.14.8
  - conda-forge::r-dtplyr=1.3.1
  - conda-forge::r-stringi=1.8.4
  - conda-forge::r-stringr=1.5.1
  - conda-forge::r-tidyverse=2.0.0
