---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::pharokka=1.9.1
  - bioconda::phanotate=1.6.7=py39h2de1943_1
