---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "pharokka_pharokka"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::pharokka=1.7.3"
