---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "archr_createarrowfiles"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "YOUR-TOOL-HERE"
