---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::toulligqc=2.7.1
  - conda-forge::huggingface_hub=0.21.1
  - conda-forge::matplotlib=3.8.4
  - conda-forge::numpy=1.26.4
  - conda-forge::pandas=2.1.4
  - conda-forge::plotly=5.24.0
  - conda-forge::python=3.11.9
