---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "bwameme_mem"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::bwa-meme=1.0.6"
  - "bioconda::mbuffer=20160228"
  - "bioconda::samtools=1.20"
