---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "macs2_callpeak"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::macs2=2.2.9.1"
