---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::demuxem=0.1.7.post1
  - conda-forge::python=3.10
  - conda-forge::numpy=1.26
  - conda-forge::pandas=2.2
