---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "seqkit_seq"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::seqkit=2.8.1"
