channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconda::bioconductor-gsva=1.46.0
  - bioconda::bioconductor-singscore=1.18.0
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-factominer=2.8.0
  - conda-forge::r-ggplot2=3.4.4
  - conda-forge::r-matrixstats=1.1.0
  - conda-forge::r-stringr=1.5.0
  - conda-forge::r-tibble=3.2.1
  - conda-forge::r-yaml=2.3.7
