# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "scsplit_count"
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.9
  - setuptools<58
  - git
  - pip
  - pip:
      - numpy
      - pandas<2.0
      - pysam
      - scikit-learn==1.1.3
      - scipy
      - statistics
      - pyVCF
