---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::sourcepredict=0.5.1
  - conda-forge::python=3.12.7
  - conda-forge::scikit-learn=1.5.2
