---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
  - bioconda::rsem=1.3.3
dependencies:
  - bioconda::rsem=1.3.3
  - bioconda::sentieon=202503.02
