---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "rtn_tni"
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-rtn=2.26.0
