---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::fastqe=0.3.3
  - conda-forge::python=3.12
  - conda-forge::setuptools=75
