---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.12.11
  - pandas=2.3.1
  - tifffile=2025.6.11
  - scikit-image=0.25.2
  - dask=2025.7.0
  - ome-types=0.6.0
  - numpy=2.3.2
  - loguru=0.7.3
  - dask-image=2024.5.3
  - zarr=3.1.1
  - pip
  - pip:
      - backsub==0.5.1