---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconda::minimap2=2.28
  - bioconda::paraphase=3.2.0
  - bioconda::samtools=1.21
