on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.nf_core_bot_auth_token }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign issues and pull requests with `new subworkflow` and `update subworkflow` label to project 38 (Hackathon Oct/2022)
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: |
          contains(github.event.issue.labels.*.name, 'new subworkflow') ||
          contains(github.event.issue.labels.*.name, 'update subworkflow') ||
          contains(github.event.pull_request.labels.*.name, 'new subworkflow') ||
          contains(github.event.pull_request.labels.*.name, 'update subworkflow')
        with:
          project: "https://github.com/orgs/nf-core/projects/38"
          column_name: "TODO"
