name: Lint Code
on: [push, pull_request]

jobs:
  Markdown:
    name: Test Markdown syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run Markdownlint
        run: markdownlint ${GITHUB_WORKSPACE} -c ${GITHUB_WORKSPACE}/.github/markdownlint.yml

  EditorConfig:
    name: Test Editor Config rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install ECLint
        run: npm install -g eclint

      - name: Run ECLint check
        run: eclint check $(git ls-files | grep -v test)

  YAML:
    name: Test YAML syntax
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install yaml-lint
        run: npm install -g yaml-lint

      - name: Run yaml-lint
        run: yamllint $(find ${GITHUB_WORKSPACE} -type f -name "*.yaml" -or -name "*.yml")
