---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::hmmer=3.3.2
  - bioconda::prodigal=2.6.3
  - numpy=1.23
  - pandas=1.3.5
  - pip:
    - traitar3==0.1.1
