---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.13.9
  - "bioconda::emu=3.5.4"
  - numpy=2.3.4
  - pandas=2.3.3
