---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::emu=3.5.4
  - conda-forge::numpy=2.3.4
  - conda-forge::pandas=2.3.3
  - conda-forge::python=3.13.9
